### ISSUE TITLE
Problem []

### ISSUE THREAD

**Issue by facuquilmes123** [Quantika14/email-prediction-asterisks#3]
Hello, thank you very much for sharing the project.
I was presented with the problem that at the end of the execution of the script it always returns this result: []
I already entered both necessary api keys but enter the data I enter I always get []

![image](https://user-images.githubusercontent.com/63804749/174460497-8e8cda19-6806-4007-aff9-259bc408e058.png)

**Comment by Quantika14** [comment]
Hello, thank you for your comment and for notifying us of the bug. Let's analyze what happens

**Comment by Quantika14** [comment]
Currently the script tries to guess the username not the domain
